// import { Inter, Shadows_Into_Light_Two } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { CartProvider } from "./components/cart/Cart";


// const shadow2 = Shadows_Into_Light_Two({ subsets: ["latin"], weight:["400"] });

export const metadata = {
  title: "www.illumine-business-hub.com",
  description: "Generated by Egwu Marvin Epie for ILLUMINE BUSINESS HUB",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CartProvider>
      <body>
        
        <Navbar />
        <div className="min-h-screen text-4xl ">
        {children}
        </div>
      
      <Footer />
      </body>
      </CartProvider>
    </html>
  );
}
