import { Inter, Shadows_Into_Light_Two } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


const shadow2 = Shadows_Into_Light_Two({ subsets: ["latin"], weight:["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={shadow2.className}>
        
        <Navbar />
        <div className="min-h-screen text-4xl ">
        {children}
        </div>
      
      <Footer />
      </body>
    </html>
  );
}
